### ISSUE TITLE
Comments Issues

### ISSUE THREAD

**Issue by absfarah** [ju1ius/css-parser#1]
Hi,

Awesome library!

I noticed whilst testing that it doesn't handle comments that are in the form:

```
/** My comment */
```

Notice the extra asterik.

Same for 

```
/*********************/
```

**Comment by ju1ius** [comment]
Thank you very much for the feedback, but I haven't been able to reproduce the issue.
Can you provide a failing test case ?
See the above commit and also https://github.com/ju1ius/css-parser/blob/master/test/bugs/GH1_Test.php

**Comment by absfarah** [comment]
Hi Ju1ius,

I just tried it again and I have realized there was a mistake in my own code. Apologies!
